appirio-tech/ng-submit-work

example/js-files.jade
src/scripts/directives/type.directive.coffee
src/views/submit-work-type.directive.jade
src/views/submit-work.directive.jade

[DEM-1097] project type markup

---

src/scripts/controllers/type.controller.coffee
src/views/submit-work-type.directive.jade

DEM-1111 update controller for type selection

---

src/styles/submit-work-type.scss
src/views/submit-work-type.directive.jade

[DEM-1148] add selected box to type section

---

src/scripts/controllers/type.controller.coffee
src/views/submit-work-type.directive.jade
tests/specs/type.controller.spec.coffee

[DEM-1149] remove save button from type

---

src/scripts/controllers/type.controller.coffee
src/scripts/directives/type.directive.coffee
tests/specs/type.controller.spec.coffee

rename type controller

---

example/css-files.jade
example/js-files.jade
example/nav.jade
example/scripts/routes.coffee
example/views/submit-work-visuals.jade
src/scripts/controllers/visual.controller.coffee
src/scripts/directives/visuals.directive.coffee
src/styles/type.scss
src/styles/visuals.scss
src/views/parts/colors.jade
src/views/parts/fonts.jade
src/views/parts/icons.jade
src/views/submit-work-features.directive.jade
src/views/submit-work-visuals.directive.jade

[DEM-1151] visual design directive markup/css

---

src/styles/type.scss
src/views/submit-work-type.directive.jade

[DEM-1174] type section new mock

---

src/scripts/controllers/features.controller.coffee
src/scripts/controllers/type.controller.coffee
src/views/submit-work-features.directive.jade
src/views/submit-work-type.directive.jade
tests/specs/type.controller.spec.coffee

Update controllers & views for new select button

---

src/scripts/controllers/development.controller.coffee
src/scripts/directives/development.directive.coffee
src/views/submit-work-development.directive.jade
tests/specs/development.controller.spec.coffee

DEM-1169 Add Development Directive

---

example/css-files.jade
src/styles/features.scss
src/styles/mixins.scss
src/styles/submit-work.scss
src/styles/type.scss
src/styles/visuals.scss
src/views/submit-work-features.directive.jade
src/views/submit-work-visuals.directive.jade

Dem 1185 - redo features layout for mobile build

---

src/scripts/controllers/features.controller.coffee
src/styles/features.scss
src/views/submit-work-features.directive.jade
tests/specs/features.controller.spec.coffee

DEM-1190 Update Features Controller

---

src/styles/development.scss
src/styles/submit-work.scss
src/styles/type.scss
src/styles/visuals.scss
src/views/submit-work-development.directive.jade
src/views/submit-work-type.directive.jade
src/views/submit-work-visuals.directive.jade

[DEM-1192] redo development seciton in mobile build

---

example/js-files.jade
src/styles/submit-work.scss
src/styles/type.scss
src/views/nav.jade
src/views/submit-work-development.directive.jade
src/views/submit-work-features.directive.jade
src/views/submit-work-visuals.directive.jade

[DEM-1203] mobile build header

---

src/views/submit-work-development.directive.jade

update development online access text

---

src/scripts/controllers/development.controller.coffee
src/scripts/controllers/visual.controller.coffee
src/views/submit-work-development.directive.jade
src/views/submit-work-visuals.directive.jade
tests/specs/development.controller.spec.coffee

DEM-1342 Refactor Development Into Modal & Fix Visuals Bugs

---

dist/main.js
src/scripts/controllers/features.controller.coffee
src/views/submit-work-features.directive.jade

DEM-1283 Modify Features Modal Behavior & Add Save Notes Button

---

src/scripts/controllers/development.controller.coffee
src/scripts/controllers/features.controller.coffee
src/scripts/controllers/visual.controller.coffee
src/views/submit-work-development.directive.jade
src/views/submit-work-features.directive.jade
src/views/submit-work-visuals.directive.jade

DEM-1284 Going Through Modals Activates Check in Main Page

---

package.json
src/scripts/controllers/visual.controller.coffee
src/styles/visuals.scss
src/views/parts/choose-styles.jade

Add Design Notes to Visuals Flow

---

src/scripts/controllers/development.controller.coffee
src/styles/development.scss
src/views/submit-work-development.directive.jade

Update Third Party Integrations Screen

---

example/nav.jade
example/scripts/development.example.controller.coffee
example/scripts/features.example.controller.coffee
example/scripts/routes.coffee
example/scripts/type-example.controller.coffee
example/scripts/visual.example.controller.coffee
example/views/submit-work-development-no-update.example.jade
example/views/submit-work-features-no-update.example.jade
example/views/submit-work-type-no-update.example.jade
example/views/submit-work-visuals-no-update.example.jade
package.json
src/scripts/controllers/development.controller.coffee
src/scripts/controllers/features.controller.coffee
src/scripts/controllers/type.controller.coffee
src/scripts/controllers/visual.controller.coffee
src/scripts/directives/development.directive.coffee
src/scripts/directives/features.directive.coffee
src/scripts/directives/type.directive.coffee
src/scripts/directives/visuals.directive.coffee
src/views/parts/choose-styles.jade
src/views/parts/define-features.jade
src/views/parts/get-style.jade
src/views/parts/upload-features.jade
src/views/parts/upload-requirements.jade
src/views/parts/visual-continue-buttons.jade
src/views/parts/visual-upload.jade
src/views/submit-work-development.directive.jade
src/views/submit-work-type.directive.jade

Dem 2183 - permission for read only
